export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_CLEAR = "LOGIN_CLEAR";

export const OTP_VARIFY_REQUEST = "OTP_VARIFY_REQUEST";
export const OTP_VARIFY_SUCCESS = "OTP_VARIFY_SUCCESS";
export const OTP_VARIFY_FAILURE = "OTP_VARIFY_FAILURE";
export const OTP_VARIFY_CLEAR = "OTP_VARIFY_CLEAR";

export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE";
export const RESEND_OTP_CLEAR = "RESEND_OTP_CLEAR";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";
export const PROFILE_CLEAR = "PROFILE_CLEAR";

export const COMMON_IMAGE_REQUEST = "COMMON_IMAGE_REQUEST";
export const COMMON_IMAGE_SUCCESS = "COMMON_IMAGE_SUCCESS";
export const COMMON_IMAGE_FAILURE = "COMMON_IMAGE_FAILURE";
export const COMMON_IMAGE_CLEAR = "COMMON_IMAGE_CLEAR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOGOUT_CLEAR = "LOGOUT_CLEAR";
export const RESET_STORE = "RESET_STORE";

// Authentication state management
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const LOGOUT = "LOGOUT";

// Territory List actions
export const TERRITORY_LIST_REQUEST = "TERRITORY_LIST_REQUEST";
export const TERRITORY_LIST_SUCCESS = "TERRITORY_LIST_SUCCESS";
export const TERRITORY_LIST_FAILURE = "TERRITORY_LIST_FAILURE";
export const TERRITORY_LIST_CLEAR = "TERRITORY_LIST_CLEAR";

// Territory List Public actions
export const TERRITORY_LIST_PUBLIC_REQUEST = "TERRITORY_LIST_PUBLIC_REQUEST";
export const TERRITORY_LIST_PUBLIC_SUCCESS = "TERRITORY_LIST_PUBLIC_SUCCESS";
export const TERRITORY_LIST_PUBLIC_FAILURE = "TERRITORY_LIST_PUBLIC_FAILURE";
export const TERRITORY_LIST_PUBLIC_CLEAR = "TERRITORY_LIST_PUBLIC_CLEAR";

export const GET_AREA_BY_PINCODE_REQUEST = 'GET_AREA_BY_PINCODE_REQUEST';
export const GET_AREA_BY_PINCODE_SUCCESS = 'GET_AREA_BY_PINCODE_SUCCESS';
export const GET_AREA_BY_PINCODE_FAILURE = 'GET_AREA_BY_PINCODE_FAILURE';
export const CLEAR_AREA_DATA = 'CLEAR_AREA_DATA';

// Territory Submission actions
export const TERRITORY_SUBMISSION_REQUEST = "TERRITORY_SUBMISSION_REQUEST";
export const TERRITORY_SUBMISSION_SUCCESS = "TERRITORY_SUBMISSION_SUCCESS";
export const TERRITORY_SUBMISSION_FAILURE = "TERRITORY_SUBMISSION_FAILURE";
export const TERRITORY_SUBMISSION_CLEAR = "TERRITORY_SUBMISSION_CLEAR";

// Contact Upload actions
export const CONTACT_UPLOAD_REQUEST = "CONTACT_UPLOAD_REQUEST";
export const CONTACT_UPLOAD_SUCCESS = "CONTACT_UPLOAD_SUCCESS";
export const CONTACT_UPLOAD_FAILURE = "CONTACT_UPLOAD_FAILURE";
export const CONTACT_UPLOAD_CLEAR = "CONTACT_UPLOAD_CLEAR";

// Get Contact List actions
export const GET_CONTACT_LIST_REQUEST = "GET_CONTACT_LIST_REQUEST";
export const GET_CONTACT_LIST_SUCCESS = "GET_CONTACT_LIST_SUCCESS";
export const GET_CONTACT_LIST_FAILURE = "GET_CONTACT_LIST_FAILURE";
export const GET_CONTACT_LIST_CLEAR = "GET_CONTACT_LIST_CLEAR";

// Invite Contact List actions
export const INVITE_CONTACT_LIST_REQUEST = "INVITE_CONTACT_LIST_REQUEST";
export const INVITE_CONTACT_LIST_SUCCESS = "INVITE_CONTACT_LIST_SUCCESS";
export const INVITE_CONTACT_LIST_FAILURE = "INVITE_CONTACT_LIST_FAILURE";
export const INVITE_CONTACT_LIST_CLEAR = "INVITE_CONTACT_LIST_CLEAR";

// My Contact List actions
export const MY_CONTACT_LIST_REQUEST = "MY_CONTACT_LIST_REQUEST";
export const MY_CONTACT_LIST_SUCCESS = "MY_CONTACT_LIST_SUCCESS";
export const MY_CONTACT_LIST_FAILURE = "MY_CONTACT_LIST_FAILURE";
export const MY_CONTACT_LIST_CLEAR = "MY_CONTACT_LIST_CLEAR";

// Add Contact actions
export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE";
export const ADD_CONTACT_CLEAR = "ADD_CONTACT_CLEAR";

// Project List actions
export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAILURE = "PROJECT_LIST_FAILURE";
export const PROJECT_LIST_CLEAR = "PROJECT_LIST_CLEAR";

// Add Project Lead actions
export const ADD_PROJECT_LEAD_REQUEST = "ADD_PROJECT_LEAD_REQUEST";
export const ADD_PROJECT_LEAD_SUCCESS = "ADD_PROJECT_LEAD_SUCCESS";
export const ADD_PROJECT_LEAD_FAILURE = "ADD_PROJECT_LEAD_FAILURE";
export const ADD_PROJECT_LEAD_CLEAR = "ADD_PROJECT_LEAD_CLEAR";

// Project Lead actions
export const PROJECT_LEAD_REQUEST = "PROJECT_LEAD_REQUEST";
export const PROJECT_LEAD_SUCCESS = "PROJECT_LEAD_SUCCESS";
export const PROJECT_LEAD_FAILURE = "PROJECT_LEAD_FAILURE";
export const PROJECT_LEAD_CLEAR = "PROJECT_LEAD_CLEAR";

// Delete User actions
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const DELETE_USER_CLEAR = "DELETE_USER_CLEAR";

// Who Am I actions
export const WHO_AM_I_REQUEST = "WHO_AM_I_REQUEST";
export const WHO_AM_I_SUCCESS = "WHO_AM_I_SUCCESS";
export const WHO_AM_I_FAILURE = "WHO_AM_I_FAILURE";
export const WHO_AM_I_CLEAR = "WHO_AM_I_CLEAR";

// Project CRM List actions
export const PROJECT_CRM_LIST_REQUEST = "PROJECT_CRM_LIST_REQUEST";
export const PROJECT_CRM_LIST_LOAD_MORE_REQUEST = "PROJECT_CRM_LIST_LOAD_MORE_REQUEST";
export const PROJECT_CRM_LIST_SUCCESS = "PROJECT_CRM_LIST_SUCCESS";
export const PROJECT_CRM_LIST_FAILURE = "PROJECT_CRM_LIST_FAILURE";
export const PROJECT_CRM_LIST_CLEAR = "PROJECT_CRM_LIST_CLEAR";

// Lead Check actions
export const LEAD_CHECK_REQUEST = "LEAD_CHECK_REQUEST";
export const LEAD_CHECK_SUCCESS = "LEAD_CHECK_SUCCESS";
export const LEAD_CHECK_FAILURE = "LEAD_CHECK_FAILURE";
export const LEAD_CHECK_CLEAR = "LEAD_CHECK_CLEAR";

// Fund Lead Check Phone Number actions
export const FUND_LEAD_CHECK_PHONE_NUMBER_REQUEST = "FUND_LEAD_CHECK_PHONE_NUMBER_REQUEST";
export const FUND_LEAD_CHECK_PHONE_NUMBER_SUCCESS = "FUND_LEAD_CHECK_PHONE_NUMBER_SUCCESS";
export const FUND_LEAD_CHECK_PHONE_NUMBER_FAILURE = "FUND_LEAD_CHECK_PHONE_NUMBER_FAILURE";
export const FUND_LEAD_CHECK_PHONE_NUMBER_CLEAR = "FUND_LEAD_CHECK_PHONE_NUMBER_CLEAR";

// Referral List actions
export const REFERRAL_LIST_REQUEST = "REFERRAL_LIST_REQUEST";
export const REFERRAL_LIST_SUCCESS = "REFERRAL_LIST_SUCCESS";
export const REFERRAL_LIST_FAILURE = "REFERRAL_LIST_FAILURE";
export const REFERRAL_LIST_CLEAR = "REFERRAL_LIST_CLEAR";

// Create Project Lead actions
export const CREATE_PROJECT_LEAD_REQUEST = "CREATE_PROJECT_LEAD_REQUEST";
export const CREATE_PROJECT_LEAD_SUCCESS = "CREATE_PROJECT_LEAD_SUCCESS";
export const CREATE_PROJECT_LEAD_FAILURE = "CREATE_PROJECT_LEAD_FAILURE";
export const CREATE_PROJECT_LEAD_CLEAR = "CREATE_PROJECT_LEAD_CLEAR";

// Project Leads List actions
export const PROJECT_LEADS_LIST_REQUEST = "PROJECT_LEADS_LIST_REQUEST";
export const PROJECT_LEADS_LIST_SUCCESS = "PROJECT_LEADS_LIST_SUCCESS";
export const PROJECT_LEADS_LIST_FAILURE = "PROJECT_LEADS_LIST_FAILURE";
export const PROJECT_LEADS_LIST_CLEAR = "PROJECT_LEADS_LIST_CLEAR";

// Project Details actions
export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAILURE = "PROJECT_DETAILS_FAILURE";
export const PROJECT_DETAILS_CLEAR = "PROJECT_DETAILS_CLEAR";

// Fund List actions
export const FUND_LIST_REQUEST = "FUND_LIST_REQUEST";
export const FUND_LIST_SUCCESS = "FUND_LIST_SUCCESS";
export const FUND_LIST_FAILURE = "FUND_LIST_FAILURE";
export const FUND_LIST_CLEAR = "FUND_LIST_CLEAR";

// Land List actions
export const LAND_LIST_REQUEST = "LAND_LIST_REQUEST";
export const LAND_LIST_SUCCESS = "LAND_LIST_SUCCESS";
export const LAND_LIST_FAILURE = "LAND_LIST_FAILURE";
export const LAND_LIST_CLEAR = "LAND_LIST_CLEAR";

export const LAND_CREATE_REQUEST = "LAND_CREATE_REQUEST";
export const LAND_CREATE_SUCCESS = "LAND_CREATE_SUCCESS";
export const LAND_CREATE_FAILURE = "LAND_CREATE_FAILURE";
export const LAND_CREATE_CLEAR = "LAND_CREATE_CLEAR";

export const LAND_UPDATE_REQUEST = "LAND_UPDATE_REQUEST";
export const LAND_UPDATE_SUCCESS = "LAND_UPDATE_SUCCESS";
export const LAND_UPDATE_FAILURE = "LAND_UPDATE_FAILURE";
export const LAND_UPDATE_CLEAR = "LAND_UPDATE_CLEAR";

// Pulses List actions
export const PULSES_LIST_REQUEST = "PULSES_LIST_REQUEST";
export const PULSES_LIST_SUCCESS = "PULSES_LIST_SUCCESS";
export const PULSES_LIST_FAILURE = "PULSES_LIST_FAILURE";
export const PULSES_LIST_CLEAR = "PULSES_LIST_CLEAR";

// Edit Profile actions
export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";
export const EDIT_PROFILE_CLEAR = "EDIT_PROFILE_CLEAR";

// Change Phone Number actions
export const CHANGE_PHONE_NUMBER_REQUEST = "CHANGE_PHONE_NUMBER_REQUEST";
export const CHANGE_PHONE_NUMBER_SUCCESS = "CHANGE_PHONE_NUMBER_SUCCESS";
export const CHANGE_PHONE_NUMBER_FAILURE = "CHANGE_PHONE_NUMBER_FAILURE";
export const CHANGE_PHONE_NUMBER_CLEAR = "CHANGE_PHONE_NUMBER_CLEAR";

// Change Phone Number Verify OTP actions
export const CHANGE_PHONE_NUMBER_VERIFY_OTP_REQUEST = "CHANGE_PHONE_NUMBER_VERIFY_OTP_REQUEST";
export const CHANGE_PHONE_NUMBER_VERIFY_OTP_SUCCESS = "CHANGE_PHONE_NUMBER_VERIFY_OTP_SUCCESS";
export const CHANGE_PHONE_NUMBER_VERIFY_OTP_FAILURE = "CHANGE_PHONE_NUMBER_VERIFY_OTP_FAILURE";
export const CHANGE_PHONE_NUMBER_VERIFY_OTP_CLEAR = "CHANGE_PHONE_NUMBER_VERIFY_OTP_CLEAR";

// Get User Profile actions
export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";
export const GET_USER_PROFILE_CLEAR = "GET_USER_PROFILE_CLEAR";

// Departments List actions
export const GET_DEPARTMENTS_LIST_REQUEST = "GET_DEPARTMENTS_LIST_REQUEST";
export const GET_DEPARTMENTS_LIST_SUCCESS = "GET_DEPARTMENTS_LIST_SUCCESS";
export const GET_DEPARTMENTS_LIST_FAILURE = "GET_DEPARTMENTS_LIST_FAILURE";
export const GET_DEPARTMENTS_LIST_CLEAR = "GET_DEPARTMENTS_LIST_CLEAR";

// Branches List actions
export const GET_BRANCHES_LIST_REQUEST = "GET_BRANCHES_LIST_REQUEST";
export const GET_BRANCHES_LIST_SUCCESS = "GET_BRANCHES_LIST_SUCCESS";
export const GET_BRANCHES_LIST_FAILURE = "GET_BRANCHES_LIST_FAILURE";
export const GET_BRANCHES_LIST_CLEAR = "GET_BRANCHES_LIST_CLEAR";

// Designations List actions
export const GET_DESIGNATIONS_LIST_REQUEST = "GET_DESIGNATIONS_LIST_REQUEST";
export const GET_DESIGNATIONS_LIST_SUCCESS = "GET_DESIGNATIONS_LIST_SUCCESS";
export const GET_DESIGNATIONS_LIST_FAILURE = "GET_DESIGNATIONS_LIST_FAILURE";
export const GET_DESIGNATIONS_LIST_CLEAR = "GET_DESIGNATIONS_LIST_CLEAR";

// Shift Managements List actions
export const GET_SHIFT_MANAGEMENTS_LIST_REQUEST = "GET_SHIFT_MANAGEMENTS_LIST_REQUEST";
export const GET_SHIFT_MANAGEMENTS_LIST_SUCCESS = "GET_SHIFT_MANAGEMENTS_LIST_SUCCESS";
export const GET_SHIFT_MANAGEMENTS_LIST_FAILURE = "GET_SHIFT_MANAGEMENTS_LIST_FAILURE";
export const GET_SHIFT_MANAGEMENTS_LIST_CLEAR = "GET_SHIFT_MANAGEMENTS_LIST_CLEAR";

// Seating Offices List actions
export const GET_SEATING_OFFICES_LIST_REQUEST = "GET_SEATING_OFFICES_LIST_REQUEST";
export const GET_SEATING_OFFICES_LIST_SUCCESS = "GET_SEATING_OFFICES_LIST_SUCCESS";
export const GET_SEATING_OFFICES_LIST_FAILURE = "GET_SEATING_OFFICES_LIST_FAILURE";
export const GET_SEATING_OFFICES_LIST_CLEAR = "GET_SEATING_OFFICES_LIST_CLEAR";

// Create Property actions
export const CREATE_PROPERTY_REQUEST = "CREATE_PROPERTY_REQUEST";
export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const CREATE_PROPERTY_FAILURE = "CREATE_PROPERTY_FAILURE";
export const CREATE_PROPERTY_CLEAR = "CREATE_PROPERTY_CLEAR";

// Property List actions
export const PROPERTY_LIST_REQUEST = "PROPERTY_LIST_REQUEST";
export const PROPERTY_LIST_SUCCESS = "PROPERTY_LIST_SUCCESS";
export const PROPERTY_LIST_FAILURE = "PROPERTY_LIST_FAILURE";
export const PROPERTY_LIST_CLEAR = "PROPERTY_LIST_CLEAR";

// Project Stages List actions
export const PROJECT_STAGES_LIST_REQUEST = "PROJECT_STAGES_LIST_REQUEST";
export const PROJECT_STAGES_LIST_SUCCESS = "PROJECT_STAGES_LIST_SUCCESS";
export const PROJECT_STAGES_LIST_FAILURE = "PROJECT_STAGES_LIST_FAILURE";
export const PROJECT_STAGES_LIST_CLEAR = "PROJECT_STAGES_LIST_CLEAR";

// Add Project Followup actions
export const ADD_PROJECT_FOLLOWUP_REQUEST = "ADD_PROJECT_FOLLOWUP_REQUEST";
export const ADD_PROJECT_FOLLOWUP_SUCCESS = "ADD_PROJECT_FOLLOWUP_SUCCESS";
export const ADD_PROJECT_FOLLOWUP_FAILURE = "ADD_PROJECT_FOLLOWUP_FAILURE";
export const ADD_PROJECT_FOLLOWUP_CLEAR = "ADD_PROJECT_FOLLOWUP_CLEAR";

// Fund Stages List actions
export const FUND_STAGES_LIST_REQUEST = "FUND_STAGES_LIST_REQUEST";
export const FUND_STAGES_LIST_SUCCESS = "FUND_STAGES_LIST_SUCCESS";
export const FUND_STAGES_LIST_FAILURE = "FUND_STAGES_LIST_FAILURE";
export const FUND_STAGES_LIST_CLEAR = "FUND_STAGES_LIST_CLEAR";

// Add Fund Followup actions
export const ADD_FUND_FOLLOWUP_REQUEST = "ADD_FUND_FOLLOWUP_REQUEST";
export const ADD_FUND_FOLLOWUP_SUCCESS = "ADD_FUND_FOLLOWUP_SUCCESS";
export const ADD_FUND_FOLLOWUP_FAILURE = "ADD_FUND_FOLLOWUP_FAILURE";
export const ADD_FUND_FOLLOWUP_CLEAR = "ADD_FUND_FOLLOWUP_CLEAR";

// Add Land Followup actions
export const ADD_LAND_FOLLOWUP_REQUEST = "ADD_LAND_FOLLOWUP_REQUEST";
export const ADD_LAND_FOLLOWUP_SUCCESS = "ADD_LAND_FOLLOWUP_SUCCESS";
export const ADD_LAND_FOLLOWUP_FAILURE = "ADD_LAND_FOLLOWUP_FAILURE";
export const ADD_LAND_FOLLOWUP_CLEAR = "ADD_LAND_FOLLOWUP_CLEAR";

// Fund Details actions
export const FUND_DETAILS_REQUEST = "FUND_DETAILS_REQUEST";
export const FUND_DETAILS_SUCCESS = "FUND_DETAILS_SUCCESS";
export const FUND_DETAILS_FAILURE = "FUND_DETAILS_FAILURE";
export const FUND_DETAILS_CLEAR = "FUND_DETAILS_CLEAR";

// Fund Projects Public List actions
export const FUND_PROJECTS_PUBLIC_LIST_REQUEST = "FUND_PROJECTS_PUBLIC_LIST_REQUEST";
export const FUND_PROJECTS_PUBLIC_LIST_SUCCESS = "FUND_PROJECTS_PUBLIC_LIST_SUCCESS";
export const FUND_PROJECTS_PUBLIC_LIST_FAILURE = "FUND_PROJECTS_PUBLIC_LIST_FAILURE";
export const FUND_PROJECTS_PUBLIC_LIST_CLEAR = "FUND_PROJECTS_PUBLIC_LIST_CLEAR";

// Fund Lead Create actions
export const FUND_LEAD_CREATE_REQUEST = "FUND_LEAD_CREATE_REQUEST";
export const FUND_LEAD_CREATE_SUCCESS = "FUND_LEAD_CREATE_SUCCESS";
export const FUND_LEAD_CREATE_FAILURE = "FUND_LEAD_CREATE_FAILURE";
export const FUND_LEAD_CREATE_CLEAR = "FUND_LEAD_CREATE_CLEAR";

// Lead Owners List actions
export const LEAD_OWNERS_LIST_REQUEST = "LEAD_OWNERS_LIST_REQUEST";
export const LEAD_OWNERS_LIST_SUCCESS = "LEAD_OWNERS_LIST_SUCCESS";
export const LEAD_OWNERS_LIST_FAILURE = "LEAD_OWNERS_LIST_FAILURE";
export const LEAD_OWNERS_LIST_CLEAR = "LEAD_OWNERS_LIST_CLEAR";

// CP Executive List actions
export const CP_EXECUTIVE_LIST_REQUEST = "CP_EXECUTIVE_LIST_REQUEST";
export const CP_EXECUTIVE_LIST_SUCCESS = "CP_EXECUTIVE_LIST_SUCCESS";
export const CP_EXECUTIVE_LIST_FAILURE = "CP_EXECUTIVE_LIST_FAILURE";
export const CP_EXECUTIVE_LIST_CLEAR = "CP_EXECUTIVE_LIST_CLEAR";

// Transfer Lead actions
export const TRANSFER_LEAD_REQUEST = "TRANSFER_LEAD_REQUEST";
export const TRANSFER_LEAD_SUCCESS = "TRANSFER_LEAD_SUCCESS";
export const TRANSFER_LEAD_FAILURE = "TRANSFER_LEAD_FAILURE";

// Fund Transfer Lead actions
export const TRANSFER_FUND_LEAD_REQUEST = "TRANSFER_FUND_LEAD_REQUEST";
export const TRANSFER_FUND_LEAD_SUCCESS = "TRANSFER_FUND_LEAD_SUCCESS";
export const TRANSFER_FUND_LEAD_FAILURE = "TRANSFER_FUND_LEAD_FAILURE";
export const TRANSFER_FUND_LEAD_CLEAR = "TRANSFER_FUND_LEAD_CLEAR";

// Pre Sales User List actions
export const PRE_SALES_USER_LIST_REQUEST = "PRE_SALES_USER_LIST_REQUEST";
export const PRE_SALES_USER_LIST_SUCCESS = "PRE_SALES_USER_LIST_SUCCESS";
export const PRE_SALES_USER_LIST_FAILURE = "PRE_SALES_USER_LIST_FAILURE";
export const PRE_SALES_USER_LIST_CLEAR = "PRE_SALES_USER_LIST_CLEAR";

// Project User List actions
export const PROJECT_USER_LIST_REQUEST = "PROJECT_USER_LIST_REQUEST";
export const PROJECT_USER_LIST_SUCCESS = "PROJECT_USER_LIST_SUCCESS";
export const PROJECT_USER_LIST_FAILURE = "PROJECT_USER_LIST_FAILURE";
export const PROJECT_USER_LIST_CLEAR = "PROJECT_USER_LIST_CLEAR";

// Fund User List actions
export const FUND_USER_LIST_REQUEST = "FUND_USER_LIST_REQUEST";
export const FUND_USER_LIST_SUCCESS = "FUND_USER_LIST_SUCCESS";
export const FUND_USER_LIST_FAILURE = "FUND_USER_LIST_FAILURE";
export const FUND_USER_LIST_CLEAR = "FUND_USER_LIST_CLEAR";

// Update Project Lead actions
export const UPDATE_PROJECT_LEAD_REQUEST = "UPDATE_PROJECT_LEAD_REQUEST";
export const UPDATE_PROJECT_LEAD_SUCCESS = "UPDATE_PROJECT_LEAD_SUCCESS";
export const UPDATE_PROJECT_LEAD_FAILURE = "UPDATE_PROJECT_LEAD_FAILURE";
export const UPDATE_PROJECT_LEAD_CLEAR = "UPDATE_PROJECT_LEAD_CLEAR";

// Update Fund Lead actions
export const UPDATE_FUND_LEAD_REQUEST = "UPDATE_FUND_LEAD_REQUEST";
export const UPDATE_FUND_LEAD_SUCCESS = "UPDATE_FUND_LEAD_SUCCESS";
export const UPDATE_FUND_LEAD_FAILURE = "UPDATE_FUND_LEAD_FAILURE";
export const UPDATE_FUND_LEAD_CLEAR = "UPDATE_FUND_LEAD_CLEAR";

// Land Details actions
export const LAND_DETAILS_REQUEST = "LAND_DETAILS_REQUEST";
export const LAND_DETAILS_SUCCESS = "LAND_DETAILS_SUCCESS";
export const LAND_DETAILS_FAILURE = "LAND_DETAILS_FAILURE";
export const LAND_DETAILS_CLEAR = "LAND_DETAILS_CLEAR";

// Land Stages List actions
export const LAND_STAGES_LIST_REQUEST = "LAND_STAGES_LIST_REQUEST";
export const LAND_STAGES_LIST_SUCCESS = "LAND_STAGES_LIST_SUCCESS";
export const LAND_STAGES_LIST_FAILURE = "LAND_STAGES_LIST_FAILURE";
export const LAND_STAGES_LIST_CLEAR = "LAND_STAGES_LIST_CLEAR";

// User Detail actions
export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAILURE = "USER_DETAIL_FAILURE";
export const USER_DETAIL_CLEAR = "USER_DETAIL_CLEAR";

// Employee Punch In actions
export const EMPLOYEE_PUNCH_IN_REQUEST = "EMPLOYEE_PUNCH_IN_REQUEST";
export const EMPLOYEE_PUNCH_IN_SUCCESS = "EMPLOYEE_PUNCH_IN_SUCCESS";
export const EMPLOYEE_PUNCH_IN_FAILURE = "EMPLOYEE_PUNCH_IN_FAILURE";
export const EMPLOYEE_PUNCH_IN_CLEAR = "EMPLOYEE_PUNCH_IN_CLEAR";

// Employee Punch Out actions
export const EMPLOYEE_PUNCH_OUT_REQUEST = "EMPLOYEE_PUNCH_OUT_REQUEST";
export const EMPLOYEE_PUNCH_OUT_SUCCESS = "EMPLOYEE_PUNCH_OUT_SUCCESS";
export const EMPLOYEE_PUNCH_OUT_FAILURE = "EMPLOYEE_PUNCH_OUT_FAILURE";
export const EMPLOYEE_PUNCH_OUT_CLEAR = "EMPLOYEE_PUNCH_OUT_CLEAR";

// Employee Face Register actions
export const EMPLOYEE_FACE_REGISTER_REQUEST = "EMPLOYEE_FACE_REGISTER_REQUEST";
export const EMPLOYEE_FACE_REGISTER_SUCCESS = "EMPLOYEE_FACE_REGISTER_SUCCESS";
export const EMPLOYEE_FACE_REGISTER_FAILURE = "EMPLOYEE_FACE_REGISTER_FAILURE";
export const EMPLOYEE_FACE_REGISTER_CLEAR = "EMPLOYEE_FACE_REGISTER_CLEAR";

// CP Create actions
export const CP_CREATE_REQUEST = "CP_CREATE_REQUEST";
export const CP_CREATE_SUCCESS = "CP_CREATE_SUCCESS";
export const CP_CREATE_FAILURE = "CP_CREATE_FAILURE";
export const CP_CREATE_CLEAR = "CP_CREATE_CLEAR";

export const CP_DETAILS_REQUEST = "CP_DETAILS_REQUEST";
export const CP_DETAILS_SUCCESS = "CP_DETAILS_SUCCESS";
export const CP_DETAILS_FAILURE = "CP_DETAILS_FAILURE";
export const CP_DETAILS_CLEAR = "CP_DETAILS_CLEAR";

export const CP_UPDATE_REQUEST = "CP_UPDATE_REQUEST";
export const CP_UPDATE_SUCCESS = "CP_UPDATE_SUCCESS";
export const CP_UPDATE_FAILURE = "CP_UPDATE_FAILURE";
export const CP_UPDATE_CLEAR = "CP_UPDATE_CLEAR";

// Channel Sales Follow Up List actions
export const CHANNEL_SALES_FOLLOW_UP_LIST_REQUEST = "CHANNEL_SALES_FOLLOW_UP_LIST_REQUEST";
export const CHANNEL_SALES_FOLLOW_UP_LIST_SUCCESS = "CHANNEL_SALES_FOLLOW_UP_LIST_SUCCESS";
export const CHANNEL_SALES_FOLLOW_UP_LIST_FAILURE = "CHANNEL_SALES_FOLLOW_UP_LIST_FAILURE";
export const CHANNEL_SALES_FOLLOW_UP_LIST_CLEAR = "CHANNEL_SALES_FOLLOW_UP_LIST_CLEAR";

// Channel Sales Stages List actions
export const CHANNEL_SALES_STAGES_LIST_REQUEST = "CHANNEL_SALES_STAGES_LIST_REQUEST";
export const CHANNEL_SALES_STAGES_LIST_SUCCESS = "CHANNEL_SALES_STAGES_LIST_SUCCESS";
export const CHANNEL_SALES_STAGES_LIST_FAILURE = "CHANNEL_SALES_STAGES_LIST_FAILURE";
export const CHANNEL_SALES_STAGES_LIST_CLEAR = "CHANNEL_SALES_STAGES_LIST_CLEAR";

// Employee Details actions
export const EMPLOYEE_DETAILS_REQUEST = "EMPLOYEE_DETAILS_REQUEST";
export const EMPLOYEE_DETAILS_SUCCESS = "EMPLOYEE_DETAILS_SUCCESS";
export const EMPLOYEE_DETAILS_FAILURE = "EMPLOYEE_DETAILS_FAILURE";
export const EMPLOYEE_DETAILS_CLEAR = "EMPLOYEE_DETAILS_CLEAR";

// Employee Punch Details by Date actions
export const EMPLOYEE_PUNCH_DETAILS_BY_DATE_REQUEST = "EMPLOYEE_PUNCH_DETAILS_BY_DATE_REQUEST";
export const EMPLOYEE_PUNCH_DETAILS_BY_DATE_SUCCESS = "EMPLOYEE_PUNCH_DETAILS_BY_DATE_SUCCESS";
export const EMPLOYEE_PUNCH_DETAILS_BY_DATE_FAILURE = "EMPLOYEE_PUNCH_DETAILS_BY_DATE_FAILURE";
export const EMPLOYEE_PUNCH_DETAILS_BY_DATE_CLEAR = "EMPLOYEE_PUNCH_DETAILS_BY_DATE_CLEAR";

// Employee Monthly Calendar actions
export const EMPLOYEE_MONTHLY_CALENDAR_REQUEST = "EMPLOYEE_MONTHLY_CALENDAR_REQUEST";
export const EMPLOYEE_MONTHLY_CALENDAR_SUCCESS = "EMPLOYEE_MONTHLY_CALENDAR_SUCCESS";
export const EMPLOYEE_MONTHLY_CALENDAR_FAILURE = "EMPLOYEE_MONTHLY_CALENDAR_FAILURE";
export const EMPLOYEE_MONTHLY_CALENDAR_CLEAR = "EMPLOYEE_MONTHLY_CALENDAR_CLEAR";

// Employee Missing Punch Request actions
export const EMPLOYEE_MISSING_PUNCH_REQUEST_REQUEST = "EMPLOYEE_MISSING_PUNCH_REQUEST_REQUEST";
export const EMPLOYEE_MISSING_PUNCH_REQUEST_SUCCESS = "EMPLOYEE_MISSING_PUNCH_REQUEST_SUCCESS";
export const EMPLOYEE_MISSING_PUNCH_REQUEST_FAILURE = "EMPLOYEE_MISSING_PUNCH_REQUEST_FAILURE";
export const EMPLOYEE_MISSING_PUNCH_REQUEST_CLEAR = "EMPLOYEE_MISSING_PUNCH_REQUEST_CLEAR";

// CP Desk Channel Sales Stages List actions
export const CP_DESK_CHANNEL_SALES_STAGES_LIST_REQUEST = "CP_DESK_CHANNEL_SALES_STAGES_LIST_REQUEST";
export const CP_DESK_CHANNEL_SALES_STAGES_LIST_SUCCESS = "CP_DESK_CHANNEL_SALES_STAGES_LIST_SUCCESS";
export const CP_DESK_CHANNEL_SALES_STAGES_LIST_FAILURE = "CP_DESK_CHANNEL_SALES_STAGES_LIST_FAILURE";
export const CP_DESK_CHANNEL_SALES_STAGES_LIST_CLEAR = "CP_DESK_CHANNEL_SALES_STAGES_LIST_CLEAR";

// CP Add Followup actions
export const CP_ADD_FOLLOWUP_REQUEST = "CP_ADD_FOLLOWUP_REQUEST";
export const CP_ADD_FOLLOWUP_SUCCESS = "CP_ADD_FOLLOWUP_SUCCESS";
export const CP_ADD_FOLLOWUP_FAILURE = "CP_ADD_FOLLOWUP_FAILURE";
export const CP_ADD_FOLLOWUP_CLEAR = "CP_ADD_FOLLOWUP_CLEAR";

//  Add feedback actions
export const FEEDBACK_REQUEST = "FEEDBACK_REQUEST";
export const FEEDBACK_SUCCESS = "FEEDBACK_SUCCESS";
export const FEEDBACK_FAILURE = "FEEDBACK_FAILURE";
export const FEEDBACK_CLEAR = "FEEDBACK_CLEAR";

//  Get feedback module list actions
export const GET_FEEDBACK_MODULE_LIST_REQUEST = "GET_FEEDBACK_MODULE_LIST_REQUEST";
export const GET_FEEDBACK_MODULE_LIST_SUCCESS = "GET_FEEDBACK_MODULE_LIST_SUCCESS";
export const GET_FEEDBACK_MODULE_LIST_FAILURE = "GET_FEEDBACK_MODULE_LIST_FAILURE";
export const GET_FEEDBACK_MODULE_LIST_CLEAR = "GET_FEEDBACK_MODULE_LIST_CLEAR";

// Professional List actions
export const GET_PROFESSIONAL_LIST_REQUEST = "GET_PROFESSIONAL_LIST_REQUEST";
export const GET_PROFESSIONAL_LIST_SUCCESS = "GET_PROFESSIONAL_LIST_SUCCESS";
export const GET_PROFESSIONAL_LIST_FAILURE = "GET_PROFESSIONAL_LIST_FAILURE";
export const GET_PROFESSIONAL_LIST_CLEAR = "GET_PROFESSIONAL_LIST_CLEAR";

// Create Professional actions
export const CREATE_PROFESSIONAL_REQUEST = "CREATE_PROFESSIONAL_REQUEST";
export const CREATE_PROFESSIONAL_SUCCESS = "CREATE_PROFESSIONAL_SUCCESS";
export const CREATE_PROFESSIONAL_FAILURE = "CREATE_PROFESSIONAL_FAILURE";
export const CREATE_PROFESSIONAL_CLEAR = "CREATE_PROFESSIONAL_CLEAR";

// Project Filter actions
export const SET_PROJECT_FILTER = "SET_PROJECT_FILTER";
export const CLEAR_PROJECT_FILTER = "CLEAR_PROJECT_FILTER";

// CP Filter actions
export const SET_CP_FILTER = "SET_CP_FILTER";
export const CLEAR_CP_FILTER = "CLEAR_CP_FILTER";

// Fund Filter actions
export const SET_FUND_FILTER = "SET_FUND_FILTER";
export const CLEAR_FUND_FILTER = "CLEAR_FUND_FILTER";