const Images = {
  // auth images
  APP_LOGO: require('../assets/images/appIcon.png'),
  LANDING_LOGO: require('../assets/images/landingIcon.png'),
  EDIT: require('../assets/images/edit.png'),
  LOGIN: require('../assets/images/login.png'),
  OTP: require('../assets/images/otp.png'),
  WATCH: require('../assets/images/watch.png'),
  PROFILE: require('../assets/images/profile.png'),
  CAMERA: require('../assets/images/camera.png'),
  CONTACT: require('../assets/images/contact.png'),
  FEEDBACK: require('../assets/images/feedback.png'),
  FOLLOW_UP: require('../assets/images/followUP.png'),
  MINI_APP: require('../assets/images/miniApp.png'),
  PLUSES: require('../assets/images/pluses.png'),
  RIDES: require('../assets/images/rid.png'),
  SETTINGS: require('../assets/images/setting.png'),
  TERROTORY: require('../assets/images/terrotory.png'),
  EMAIL: require('../assets/images/email.png'),
  BACK: require('../assets/images/back.png'),
  SEARCH: require('../assets/images/search.png'),
  CONTACT_SYNC: require('../assets/images/contactSync.png'),
  SCANNER: require('../assets/images/scanner.png'),
  CALENDAR: require('../assets/images/calendar.png'),
  LAND: require('../assets/images/land.png'),
  PROJECT: require('../assets/images/project.png'),
  SHARE: require('../assets/images/share.png'),
  PLUS: require('../assets/images/plus.png'),
  PUNCH_SYSTEM: require('../assets/images/employee.png'),
  CALL: require('../assets/images/call.png'),
  WHATSAPP: require('../assets/images/wp.png'),
  ARROW: require('../assets/images/arrow.png'),
  PROJECTS: require('../assets/images/projects.png'),
  LANDS: require('../assets/images/lands.png'),
  ATTENDANCE: require('../assets/images/attendence.png'),
  DROPDOWN: require('../assets/images/dropdown.png'),
  LOCATION: require('../assets/images/location.png'),
  LEAD_TRANSFER : require('../assets/images/leadTrasfer.png'),
  NO_DATA: require('../assets/images/noData.png'),
  CAMERAS: require("../assets/images/addPhoto.png"),
  GALLARY: require("../assets/images/GalleryIcon.png"),
  FILE: require("../assets/images/files.png"),
  FILTER: require("../assets/images/filter.png"),
  FACE_VERIFY: require("../assets/images/employees.png"),
  TIMER: require("../assets/images/timer.png"),
  CP: require("../assets/images/cp.png"),
  COMMUNITY: require("../assets/images/community.png"),
  HOME: require("../assets/images/home.png"),
  RID: require("../assets/images/r-id.png"),
  UNIVERSAL: require("../assets/images/universe.gif"),
  TIME_SHEET: require('../assets/images/timesheet.png'),
  SCAN: require('../assets/images/scanners.png'),
  ALERT: require('../assets/images/Alert.png'),
  GREEN_ARROW: require('../assets/images/greenarrow.png'),
  RED_ARROW: require('../assets/images/redarrow.png'),
  WATCHCAL: require('../assets/images/watchCal.png'),
  TERRITORY: require('../assets/images/territory.png'),
};

export default Images;
