import { StyleSheet } from "react-native";
import { COLORS, FF, FS } from "../../../constants";

const SettingStyles = StyleSheet.create({
    container: {
        flex: 1,
        // backgroundColor: COLORS.BG_GREY,
        paddingHorizontal: 0,
        paddingTop: 0,
    },
    contentWrapper: {
        flex: 1,
        alignItems: 'center',
        paddingTop: 24,
        paddingHorizontal: 0,
    },
    card: {
        width: '90%',
        borderRadius: 12,
        // Linear gradient will be applied via LinearGradient component
        alignSelf: 'center',
    },
    profileCard: {
        width: '90%',
        backgroundColor: COLORS.WHITE,
        borderRadius: 12,
        padding: 20,
        marginBottom: 20,
        shadowColor: COLORS.BLACK,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        alignSelf: 'center',
    },
    cardTitle: {
        fontFamily: FF[600],
        fontSize: FS.FS16,
        color: COLORS.BLACK_TEXT,
        marginBottom: 12,
    },
    profileRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    profileAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: COLORS.GREY_TEXT,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    profileAvatarText: {
        color: COLORS.WHITE,
        fontFamily: FF[700],
        fontSize: FS.FS20,
    },
    profileInfo: {
        flex: 1,
    },
    profileName: {
        fontFamily: FF[600],
        fontSize: FS.FS18,
        color: COLORS.BLACK_TEXT,
        marginBottom: 8,
    },
    phoneContainer: {
        // borderWidth: 1,
        // borderColor: '#E3F2FD',
        // borderRadius: 8,
        // paddingHorizontal: 12,
        // paddingVertical: 6,
        // alignSelf: 'flex-start',
    },
    phoneText: {
        fontFamily: FF[400],
        fontSize: FS.FS14,
        color: COLORS.GREY_TEXT,
    },
    avatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: COLORS.GREY_TEXT,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    avatarText: {
        color: COLORS.WHITE,
        fontFamily: FF[700],
        fontSize: FS.FS20,
    },
    info: {
        flex: 1,
    },
    name: {
        fontFamily: FF[400],
        fontSize: FS.FS24,
        color: COLORS.BLACK_TEXT,
    },
    rid: {
        fontFamily: FF[400],
        fontSize: FS.FS18,
        color: COLORS.GREY_TEXT,
        marginTop: 6,
    },
    section: {
        width: '90%',
        alignSelf: 'center',
        // marginBottom: 16,
    },
    listItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.WHITE,
        borderRadius: 12,
        paddingVertical: 18,
        paddingHorizontal: 18,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: COLORS.BORDER_GREY,
    },
    listItemDisabled: {
        opacity: 0.5,
    },
    icon: {
        marginRight: 16,
        width: 22,
        height: 22,
        alignItems: 'center',
        justifyContent: 'center',
    },
    listText: {
        fontFamily: FF[500],
        fontSize: FS.FS15,
        color: COLORS.BLACK_TEXT,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: "#FBFBFB",
        borderRadius: 12,
        paddingVertical: 18,
        paddingHorizontal: 18,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: COLORS.BORDER_GREY,
        shadowColor: COLORS.BLACK,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    menuItemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    menuIcon: {
        fontSize: 20,
        marginRight: 12,
    },
    menuText: {
        fontFamily: FF[500],
        fontSize: FS.FS15,
        color: COLORS.BLACK_TEXT,
    },
    chevron: {
        width: 16,
        height: 16,
        resizeMode: 'contain',
        tintColor: COLORS.GREY_TEXT,
        transform: [{ rotate: '180deg' }],
    },
    logoutItem: {
        alignItems: 'center',
        backgroundColor: COLORS.WHITE,
        borderRadius: 12,
        paddingVertical: 18,
        paddingHorizontal: 18,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: COLORS.BORDER_GREY,
    },
    deleteItem: {
        alignItems: 'center',
        backgroundColor: COLORS.WHITE,
        borderRadius: 12,
        paddingVertical: 18,
        paddingHorizontal: 18,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: COLORS.BORDER_GREY,
    },
    logoutIcon: {
        marginRight: 16,
        width: 22,
        height: 22,
        alignItems: 'center',
        justifyContent: 'center',
    },
    logoutText: {
        fontFamily: FF[500],
        fontSize: FS.FS15,
        color: 'red',
    },
    deleteText: {
        fontFamily: FF[500],
        fontSize: FS.FS15,
        color: 'red',
    },
    spacer: {
        height: 20,
    },
    actionSection: {
        width: '90%',
        alignSelf: 'center',
        marginTop: 20,
    },
    actionButton: {
        alignItems: 'center',
        backgroundColor: COLORS.WHITE,
        borderRadius: 12,
        paddingVertical: 24,
        paddingHorizontal: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        shadowColor: COLORS.BLACK,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    actionButtonText: {
        fontFamily: FF[500],
        fontSize: FS.FS16,
        color: COLORS.BLACK_TEXT,
    },
    versionContainer: {
        paddingVertical: 30,
        alignItems: 'center',
    },
    versionText: {
        fontFamily: FF[400],
        fontSize: FS.FS13,
        color: COLORS.GREY_TEXT,
    },
    profileCardTouch: {
        paddingVertical: 20,
        paddingHorizontal: 20,
    },
    profileEmail: {
        fontSize: 13,
        color: COLORS.GREY_TEXT,
        marginTop: 4,
    },
    unitInfoCard: {
        marginTop: 16,
        backgroundColor: '#E3F2FD',
        padding: 16,
        borderRadius: 8,
        width: '90%',
        alignSelf: 'center',
    },
    unitLabel: {
        fontSize: 12,
        color: COLORS.GREY_TEXT,
        marginBottom: 4,
    },
    unitText: {
        fontSize: 18,
        fontFamily: FF[600],
        color: COLORS.BLACK,
        marginBottom: 2,
    },
    badgeRow: {
        flexDirection: 'row',
        marginTop: 8,
    },
    residentBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        marginRight: 8,
    },
    badgeText: {
        color: COLORS.WHITE,
        fontSize: 11,
        fontFamily: FF[600],
    },
    memberSinceText: {
        fontSize: 12,
        color: COLORS.GREY_TEXT,
        alignSelf: 'center',
    },
    scrollView: {
        flex: 1,
        width: '100%',
    },
    sectionMarginTop: {
        marginTop: 16,
    },
    ownerBadge: {
        backgroundColor: '#4CAF50',
    },
    tenantBadge: {
        backgroundColor: '#2196F3',
    },
});

export default SettingStyles;