import { StyleSheet } from "react-native";
import { COLORS, FF, FS, LH } from "../../../constants";

const ProjectStyles = StyleSheet.create({
    container: {
      // padding: 12,
    },
    card: {
      backgroundColor: COLORS.WHITE,
      borderRadius: 12,
      marginBottom: 16,
      width: '100%',
      overflow: 'hidden',
      elevation: 3,
      shadowColor: COLORS.BLACK,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      borderWidth: 1,
      borderColor: COLORS.BORDER_GREY,
    },
    imageContainer: {
      position: 'relative',
      height: 203,
    },
    image: {
      width: '100%',
      // height:200,
      height: '100%',
      borderTopRightRadius:14,
      borderTopLeftRadius:14,
      overflow:'hidden',
      resizeMode:'cover',

      // borderRadius:8
    },
    statusTag: {
      position: 'absolute',
      top: 10,
      right: 10,
      paddingHorizontal: 8,
      paddingVertical: 8,
      borderRadius: 6,
      backgroundColor:COLORS.WHITE,
    },
    statusText: {
      fontSize: FS.FS12,
      fontFamily: FF[400],
      color: COLORS.BLACK,
    },
    priceBadge: {
      position: 'absolute',
      bottom: 10,
      left: 10,
      backgroundColor: 'rgba(0,0,0,0.9)',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
      zIndex: 1,
    },
    priceBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: COLORS.WHITE,
      letterSpacing: 0.5,
    },
    typeBadge: {
      position: 'absolute',
      top: 10,
      left: 10,
      backgroundColor: 'rgba(255,255,255,0.95)',
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 10,
    },
    typeBadgeText: {
      fontSize: 9,
      fontWeight: '600',
      color: COLORS.BLACK_TEXT,
    },
    imageCountBadge: {
      position: 'absolute',
      bottom: 10,
      right: 10,
      backgroundColor: 'rgba(0,0,0,0.7)',
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 10,
    },
    imageCountText: {
      fontSize: 9,
      fontWeight: '600',
      color: COLORS.WHITE,
    },
    loadingContainer: {
      paddingVertical: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loadingText: {
      color: COLORS.GREY_TEXT,
      fontSize: 14,
      fontWeight: '500',
    },
    content: {
      // padding: 12,
      flexDirection:'row',
      justifyContent:'space-between',
      alignItems:'center',
      // padding:12,
    },
    headerRow: {
      marginBottom: 8,
    },
    title: {
      fontSize: FS.FS18,
      fontFamily: FF[500],
      // marginBottom: 4,
      color: COLORS.BLACK,
      lineHeight: 22,
    },
    locationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    // locationIcon: {
    //   fontSize: 12,
    //   marginRight: 4,
    // },
    location: {
      fontSize: FS.FS16,
      color: COLORS.GREY_TEXT,
      fontFamily: FF[400],
    },
    description: {
      fontSize: FS.FS16,
      color: COLORS.GREY_TEXT,
      fontFamily: FF[400],
      lineHeight: LH.LH24,
      marginTop: 16,
    },
    detailsRow: {
      flexDirection: 'row',
      // marginBottom: 10,
      gap: 10,
    },
    detailItem: {
      // flex: 1,
    },
    detailLabel: {
      fontSize: 10,
      color: COLORS.GREY_TEXT,
      fontWeight: '600',
      marginBottom: 2,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    detailValue: {
      fontSize: 11,
      color: COLORS.BLACK_TEXT,
      fontWeight: '600',
    },
    featuresSection: {
      marginBottom: 8,
    },
    featureGroup: {
      marginBottom: 6,
    },
    featureLabel: {
      fontSize: 10,
      color: COLORS.GREY_TEXT,
      fontWeight: '600',
      marginBottom: 4,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    featureTags: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    connectivityTag: {
      backgroundColor: '#F0F9FF',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    connectivityText: {
      fontSize: 10,
      color: '#0369A1',
      fontWeight: '500',
    },
    amenityTag: {
      backgroundColor: '#F0FDF4',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    amenityText: {
      fontSize: 10,
      color: '#166534',
      fontWeight: '500',
    },
    greenFeaturesSection: {
      marginBottom: 10,
    },
    greenFeatureTag: {
      backgroundColor: '#FEF3C7',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    greenFeatureText: {
      fontSize: 10,
      color: '#92400E',
      fontWeight: '500',
    },
    bottomRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 10,
    },
    leadButton: {
      backgroundColor: COLORS.BLUE_TEXT,
      paddingVertical: 8,
      paddingHorizontal: 8,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      width: 40,
      height: 40,
    },
    leadButtonText: {
      fontSize: 16,
      color: COLORS.WHITE,
    },
    shareButton: {
      backgroundColor: COLORS.BLACK,
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    shareButtonText: {
      fontSize: FS.FS16,
      color: COLORS.WHITE,
      fontFamily: FF[500],
    },
    // Share Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    shareModalContent: {
      backgroundColor: COLORS.WHITE,
      borderRadius: 20,
      width: '90%',
      maxHeight: '70%',
      elevation: 5,
      shadowColor: COLORS.BLACK,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      paddingBottom: 16,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.BORDER_GREY,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: COLORS.BLACK_TEXT,
    },
    closeButton: {
      padding: 4,
    },
    closeButtonText: {
      fontSize: 20,
      color: COLORS.GREY_TEXT,
      fontWeight: '600',
    },
    shareOptionsContainer: {
      padding: 20,
    },
    shareOptionsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    shareOptionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '48%',
      marginBottom: 20,
    },
    shareOptionLabel: {
      fontSize: FS.FS16,
      fontFamily: FF[400],
      color: COLORS.BLACK,
      marginLeft: 12,
      flex: 1,
    },
    shareOptionValue: {
      fontSize: 14,
      color: COLORS.GREY_TEXT,
      flex: 1,
      flexWrap: 'wrap',
    },
    shareOptionImage: {
      width: 48,
      height: 48,
      borderRadius: 8,
      marginLeft: 8,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: COLORS.BORDER_GREY,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: COLORS.WHITE,
    },
    checkboxChecked: {
      backgroundColor: COLORS.BLACK,
      borderColor: COLORS.BLACK,
    },
    checkboxText: {
      color: COLORS.WHITE,
      fontSize: 12,
      fontWeight: 'bold',
    },
    modalFooter: {
      alignItems:'center',
      alignSelf:'center',
      // padding: 20,
      // paddingTop: 10,
    },
  });

  export default ProjectStyles;